global:
  scrape_interval: 15s #默认15s采集一次
  external_labels:
    monitor: 'go-micro-common'
scrape_configs:
  # 监控的服务
  - job_name: 'account'
    scrape_interval: 5s #覆盖默认值
    static_configs:
      - targets: ['192.168.1.4:9092']